# Generated by Django 4.0.6 on 2022-07-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='imageLink',
            field=models.CharField(default='none', max_length=3500),
        ),
    ]
