# Generated by Django 4.0.6 on 2022-07-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_imagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='imageLink',
            field=models.CharField(default='http://books-world-pranshu1902.herokuapp.com/static/default.png', max_length=3500),
        ),
    ]
