# Generated by Django 4.0.6 on 2022-07-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_imagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='imageLink',
            field=models.CharField(blank=True, default='http://books-world-pranshu1902.herokuapp.com/static/default.png', max_length=3500, null=True),
        ),
    ]
